# Generated by Django 6.0.3 on 2026-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=36)),
                ('user_id', models.CharField(max_length=50)),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('quiz_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('question_ids', models.JSONField()),
                ('current_index', models.IntegerField(default=0)),
            ],
        ),
    ]
