# Generated by Django 6.0.3 on 2026-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('choices', models.JSONField()),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
